### ISSUE TITLE
Black Screenshot

### ISSUE THREAD

**Issue by xXPerditorXx** [flo2002/all_games_trigger_bot#2]
If i start the script my window is just black
![grafik](https://user-images.githubusercontent.com/60017046/120468771-df64ac80-c3a1-11eb-991c-11c8a46aa1dd.png)

I changed a little bit so it captures my second screen
![grafik](https://user-images.githubusercontent.com/60017046/120469032-28b4fc00-c3a2-11eb-9fff-277952be97ea.png)

**Comment by flo2002** [comment]
Are you sure that you have that much pixels on your monitor? On which System are you working on? (OS, Python versions, ...)

**Comment by xXPerditorXx** [comment]
Windows 10, 3.9.2 Python Version

I checked with pyautogui.location() where my mouse is.

**Comment by flo2002** [comment]
Can you make a picture, if you delete "region=(2870, 535, 10, 10)"? Which GPU driver are you using?

**Comment by xXPerditorXx** [comment]
Yes i can take a picture but i want a picture of my second screen. GPU Driver is NVIDIA Game Ready Driver (GTX 1050)

**Comment by flo2002** [comment]
Ok, there are two solutions possible:

1. **The quick and easy one**: Change the primary monitor in your operating system.
2. **The tricky one**: Use an other module for the screenshot function, which allows you to select the monitor. The module used in this code "pyautogui" can't do that (up to now). Modules which can do it are "mss" or "pil". Source: [https://stackoverflow.com/questions/63737476/screenshot-on-multiple-monitor-setup-pyautogui](url)
